services:
  sampleapp:
    image: ghcr.io/jyothipriyag/sampleapp:v3
    depends_on:
            mysql:
                condition: service_healthy
    environment:
      NAME: "Dhanvith"
      DB_HOST: "10.0.0.20"
    networks:
      my_shared_network:
        ipv4_address: 10.0.0.10
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: mysql # Required: Sets the root password
      MYSQL_DATABASE: testdb # Optional: Creates a default database
    ports:
      - "3306:3306"
    healthcheck: # Health check configuration
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"] 
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      my_shared_network:
        ipv4_address: 10.0.0.20
networks:
  my_shared_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24 # Define the subnet for the network
          gateway: 10.0.0.1 # Define the gateway for the network

